### ISSUE TITLE
Support nib files

### ISSUE THREAD

**Issue by st3fan** [st3fan/ewm#82]
A lot of disk images are in `.nib` format.

**Comment by paulhagstrom** [comment]
.nib format is $1a00 (6656) nibbles per track, 35 tracks (0-34, $00-$22). It's just the same as the nibbles that dsk_convert_sector() produces. So, you can probably just read the data straight into drive->tracks.

**Comment by paulhagstrom** [comment]
Two other related comments about .nib format: The .nib format is required for preserving the volume number (you noted in a comment that .dsk format throws away the volume number, which is true), and occasionally programs do rely on the volume number for disk identification. It is also required for preserving 13-sector disks (which just use a different nibble scheme), since .dsk format is only defined for 16-sector disks. There is in principle a .d13 format that is like .dsk but for 13-sector disks, but as far as I know very few if any emulators support it, so there aren't many .d13 images out there. (CiderPress can handle them, though.)

**Comment by st3fan** [comment]
@paulhagstrom Thanks for the hints! This was pretty easy to implement.
